# Generated by Django 4.1.1 on 2022-10-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('Ksh', 'Ksh')], max_length=100, null=True, verbose_name='Choose Currency'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='log',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='grant',
            name='person_responsible',
            field=models.CharField(default='Jesica', max_length=100, verbose_name='Choose Persons'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='thematic_area',
            field=models.CharField(choices=[('SRHR', 'SRHR'), ('HIV/TB', 'HIV/TB'), ('WLPR', 'WLPR'), ('SILU', 'SILU'), ('H&G', 'H&G')], max_length=100, verbose_name='Choose Thematic'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
